%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Users/gabrielsousa/Desktop/untitled folder/OPERACAO.TXT
%
% Auto-generated by MATLAB on 31-May-2019 19:10:26

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 1);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = "VarName1";
opts.VariableTypes = "double";
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
OPERACAO = readtable("/Users/gabrielsousa/Desktop/untitled folder/OPERACAO.TXT", opts);

%% Convert to output type
x = table2array(OPERACAO);

%% Clear temporary variables
clear opts